config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?
  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone, :role, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone, :role, :email, :password, :password_confirmation])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]
  before_action :authenticate_receptionist!, only: [:new, :create, :edit, :update, :destroy]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
    @graph_data = Patient.group_by_day(:created_at).count
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name, :phone, :age, :email, :address,)
    end

    def authenticate_receptionist!
      redirect_to patients_path, alert: "You don't have access to this action" unless current_user.role == "Receptionist"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/home/index.html.erb
<h1 class="home-title">Welcome to the patients manager app</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodingAssessmentMakerable</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
      <script>
         document.addEventListener('DOMContentLoaded', function() {
           setInterval(function() {
            const alertElement = document.querySelector('.alert');
            const noticeElement = document.querySelector('.notice');
              if (alertElement) {
                setTimeout(() => {
                  alertElement.style.display = 'none';
                }, 3000);
              }
              if (noticeElement) {
                setTimeout(() => {
                  noticeElement.style.display = 'none';
                }, 3000);
              }
            }, 1000); // Adjust the time in milliseconds (here, it's 3000 milliseconds or 3 seconds)
          });
      </script>
    <div class="main-div">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient, html:{class: 'patient-form'}) do |form| %>
  <% if patient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>


  <div >
     <%= form.submit "Submit", class: "btn"  %>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<div id="<%= dom_id patient %>" class="patient-info">
  <p>
    <strong>Name:</strong>
    <%= patient.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= patient.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= patient.email %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= patient.address %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= patient.age %>
  </p>
</div>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Show this patient", @patient %> |
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/index.html.erb
<div class="patients-page">
  <h1>Patients</h1>
  <% if @patients.size > 0  %>
    <div class="patients-holder">
      <% @patients.each do |patient| %>
        <%= render patient %>
        <p>
          <%= link_to "Show", patient_path(patient) %>
        </p>
      <% end %>
    </div>
  <% else %>
    <p>There are no patients.</p>
  <% end %>
  <% if current_user.role == 'Receptionist'%>
    <%= link_to "New patient", new_patient_path, class: "btn" %>
    <div id="patients">
    </div>

  <% else %>
    <h2>Patients Registered Over Days</h2>
    <%= column_chart @graph_data, id: "patients-chart", title: 'Patients over days', xtitle: "Date", ytitle: "Patients", empty: "No patients"  %>
  <%end%>
</div>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/show.html.erb
<%= render @patient %>

<div class="show-patient-btns">
  <% if current_user.role == 'Receptionist' %>
    <%= button_to "Destroy this patient", @patient, method: :delete, class:'btn' %>
    <%= link_to "Edit this patient", edit_patient_path(@patient), class:'btn' %> 
  <% end %>
    <%= link_to "Back to patients", patients_path, class:'btn' %>
</div>

app/views/shared/_navbar.html.erb
<nav class="nav">
  <div class="nav__logo">
    <span class="nav-bar-title">
      Patients manager
    </span>
  </div>
  <ul class="nav-ul">
    <li><%= link_to "Home", root_path %></li>
    <% if current_user%>
      <li> <%= link_to "Patients", patients_path %> </li>
      <li><%= button_to "Logout", destroy_user_session_path, method: :delete, class:"btn" %></li>
    <% else %>
      <li><%= link_to "Login", new_user_session_path %></li>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
    <% end %>
  </ul>
</nav>